import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DEFAULT_FSRS_W, type JobContext } from '@retenia/core'
import { describe, expect, it } from 'vitest'
import { createFsrsOptimizeJob, type FsrsOptimizeResult } from './fsrs-optimize'

/**
 * The optimizer, against a real training run (`docs/spec/02-memory-system.md` §6, §16).
 *
 * The fixture is a 5,000-review history generated *from* a known set of parameters
 * (`packages/core/src/testing/optimizer-fixture.ts`), so "the optimizer improves log loss"
 * is a structural claim rather than luck: the data is FSRS-6 sampled somewhere the defaults
 * are not, and moving toward that point is the trainer's whole job.
 *
 * It is also a cross-implementation check. The history is generated by our TypeScript closed
 * forms in `memory/formulas.ts`; the training and both evaluations are `fsrs-rs`'s Rust. The
 * two agreeing closely enough for the trained model to land on the ground truth is evidence
 * neither could give alone.
 */

const require_ = createRequire(import.meta.url)
const bindingAvailable = (() => {
  try {
    require_.resolve('@open-spaced-repetition/binding')
    return true
  } catch {
    return false
  }
})()

const here = fileURLToPath(new URL('.', import.meta.url))
const FIXTURE = join(here, '__fixtures__', 'fsrs-5k.csv')

function context(): JobContext & { stages: Array<[number, string | undefined]> } {
  const stages: Array<[number, string | undefined]> = []
  return {
    jobId: 'test-job',
    progress: (value, message) => stages.push([value, message]),
    signal: { aborted: false, addEventListener: () => {}, removeEventListener: () => {} },
    log: { info: () => {}, warn: () => {}, error: () => {} },
    stages,
  }
}

const input = (currentW: readonly number[] = DEFAULT_FSRS_W) => ({
  path: FIXTURE,
  currentW: [...currentW],
  nextDayStartsAt: 4,
  timeZone: 'UTC',
  enableShortTerm: true,
  numRelearningSteps: 1,
})

describe('the fixture', () => {
  it('is the 5,000-review history the acceptance criterion names', () => {
    const rows = readFileSync(FIXTURE, 'utf8')
      .split('\n')
      .filter((line) => line.length > 0)
    expect(rows[0]).toBe('card_id,review_time,review_rating,review_state,review_duration')
    expect(rows).toHaveLength(5_001)
  })
})

/**
 * The binding publishes prebuilt N-API binaries for every platform this app ships on, plus a
 * `wasm32-wasi` build behind the same API — so on CI (windows-latest and ubuntu-latest) this
 * suite is expected to *run*, not skip. The guard below is what makes a silent resolve
 * failure a red test rather than a green skip.
 */
describe('the optimizer binding', () => {
  it('resolves on every platform we ship', () => {
    const shipped =
      ['win32', 'linux', 'darwin'].includes(process.platform) &&
      ['x64', 'arm64'].includes(process.arch)
    if (shipped) expect(bindingAvailable).toBe(true)
    else expect(typeof bindingAvailable).toBe('boolean')
  })
})

describe.skipIf(!bindingAvailable)('fsrsOptimize (§6, §16)', () => {
  const job = createFsrsOptimizeJob([here])

  it('trains on the 5k fixture and improves on the published defaults', async () => {
    const ctx = context()
    const result = (await job.run(input(), ctx)) as FsrsOptimizeResult

    expect(result.nReviews).toBe(5_000)
    // One item is a card's whole history, so there are fewer of them than reviews.
    expect(result.nItems).toBeGreaterThan(0)
    expect(result.nItems).toBeLessThan(result.nReviews)
    expect(result.w).toHaveLength(21)
    expect(result.decay).toBe(result.w[20])

    // The acceptance criterion.
    expect(result.after.logLoss).toBeLessThan(result.before.logLoss)
    // Measured on this fixture: 0.3783 → 0.3558. Bounded rather than pinned, so an
    // unrelated change to the trainer or the formulas fails loudly without this test
    // becoming a version pin.
    expect(result.before.logLoss).toBeGreaterThan(0.36)
    expect(result.after.logLoss).toBeLessThan(0.37)
    // Calibration improves too, though §16 gates on log loss alone.
    expect(result.after.rmse).toBeLessThan(result.before.rmse)

    // Stage-based, because the binding's own `progress` callback never fires.
    expect(ctx.stages.map(([, message]) => message)).toEqual([
      'reading the review history',
      'converting to FSRS items',
      'measuring the current parameters',
      'training',
      'measuring the trained parameters',
      'done',
    ])
    expect(ctx.stages.at(-1)?.[0]).toBe(1)
  })

  /**
   * The rejection half of the acceptance criterion, produced deterministically rather than
   * with a second, hand-tuned fixture: training is deterministic, so re-training on
   * unchanged history reproduces the same parameters and cannot beat itself. Equal is not
   * better (`healthCheck`), so the health check refuses it.
   */
  it('cannot improve on parameters it just produced', async () => {
    const first = (await job.run(input(), context())) as FsrsOptimizeResult
    const second = (await job.run(input(first.w), context())) as FsrsOptimizeResult

    expect(second.w).toEqual(first.w)
    expect(second.before.logLoss).toBeCloseTo(second.after.logLoss, 12)
    expect(second.after.logLoss < second.before.logLoss).toBe(false)
  })

  it('refuses a path outside the directories it may read', async () => {
    const confined = createFsrsOptimizeJob([join(here, 'nowhere')])
    await expect(confined.run(input(), context())).rejects.toThrow(/outside the directories/)
  })

  it('stops when the job is cancelled', async () => {
    const ctx = context()
    const aborted: JobContext = {
      ...ctx,
      signal: { aborted: true, addEventListener: () => {}, removeEventListener: () => {} },
    }
    await expect(job.run(input(), aborted)).rejects.toThrow(/cancelled/i)
  })

  it('rejects a payload it does not recognise', () => {
    expect(() => job.parseInput({ ...input(), path: '' })).toThrow(/path/)
    expect(() => job.parseInput({ ...input(), currentW: [1, 2] })).toThrow(/currentW/)
    expect(() => job.parseInput({ ...input(), nextDayStartsAt: 24 })).toThrow(/nextDayStartsAt/)
    expect(() => job.parseInput({ ...input(), timeZone: '' })).toThrow(/timeZone/)
  })
})
