export {
  CITE_MARKER,
  type Claim,
  citeIdsIn,
  claimId,
  extractClaims,
  MIN_CLAIM_CHARS,
  removeCiteIds,
  type Segment,
  segmentSentences,
  stripMarkers,
  stripSegmentMarkers,
} from './claims'
export {
  MIN_TOKEN_OVERLAP,
  normalizeForMatch,
  QUOTED_SPAN,
  quotedSpans,
  SPAN_SIMILARITY_THRESHOLD,
  spanMatches,
  spanSimilarity,
} from './fuzzy'
export * from './gates'
export {
  LESSON_QA_VERSION,
  type LessonQa,
  type LessonQaSummary,
  lessonQaSchema,
  MAX_FINDING_SENTENCE_CHARS,
  MAX_FINDINGS,
  QA_FINDING_KINDS,
  QA_GATE_OUTCOMES,
  QA_GATES,
  QA_MODES,
  QA_VERDICTS,
  type QaFinding,
  type QaFindingKind,
  type QaGate,
  type QaGateOutcome,
  type QaMode,
  type QaVerdict,
  qaFindingSchema,
  readLessonQa,
  summarizeQa,
} from './lesson-qa'
export { type PersistQaInput, persistQa } from './persist'
export {
  createQaPipeline,
  DEFAULT_QA_CONCURRENCY,
  type QaLessonInput,
  type QaLessonOutcome,
  type QaPipeline,
  type QaPipelineDeps,
  type QaProgress,
  type QaRepos,
  type QaRunInput,
  type QaRunResult,
  runQaGates,
} from './pipeline'
export {
  buildEditRequest,
  buildFaithfulnessRequest,
  buildJudgeRequest,
  EDIT_LESSON_MAX_OUTPUT_TOKENS,
  EDIT_LESSON_STAGE,
  editCustomId,
  FAITHFULNESS_MAX_OUTPUT_TOKENS,
  FAITHFULNESS_STAGE,
  faithfulnessCustomId,
  judgeCustomId,
  PEDAGOGY_JUDGE_MAX_OUTPUT_TOKENS,
  PEDAGOGY_JUDGE_STAGE,
  type QaRequest,
  type QaRequestOptions,
} from './requests'
export {
  buildEditTask,
  buildFaithfulnessTask,
  buildJudgeTask,
  type EditTaskInput,
  type FaithfulnessTaskInput,
  type JudgeTaskInput,
  type QaTask,
} from './tasks'
