import { describe, expect, it } from 'vitest'
import raw from '../../test/fixtures/fsrs/py-fsrs.json'
import { cardFixture } from '../testing/memory-fixtures'
import { scheduledInterval } from './formulas'
import { createFsrsScheduler, type FsrsScheduler } from './fsrs-scheduler'
import { stepUnitToMinutes } from './parameters'
import { DAY_MS } from './study-day'
import { CARD_STATE, type Grade, type SchedulingOptions, type StepUnit } from './types'

/**
 * Regression suite against py-fsrs (`docs/spec/02-memory-system.md` §5): every transition
 * of `test/fixtures/fsrs/py-fsrs.json` — generated by `tooling/fsrs-fixtures/gen.py` with
 * the pinned py-fsrs — replayed through `FsrsScheduler`.
 *
 * Where ts-fsrs and py-fsrs disagree, the scheduler must follow ts-fsrs, and the test
 * says so instead of loosening a tolerance. The discrepancies, each asserted below and
 * counted so the list stays honest (a documented difference that never shows up in the
 * data fails the suite):
 *
 * 1. **Initial stability floor.** `S0 = max(w[G−1], 0.1)` in ts-fsrs, `0.001` in py-fsrs.
 *    Visible only when a parameter is below 0.1 (the `s0-clamp` configuration).
 * 2. **Same-day Hard mask.** ts-fsrs masks the short-term increase to ≥ 1 for Hard, Good
 *    and Easy; py-fsrs ≤ 6.3.1 did so only for Good and Easy. py-fsrs 6.3.2 — the pinned
 *    version — agrees with ts-fsrs, so this one is asserted directly rather than counted.
 * 3. **Hard inside the learning steps.** ts-fsrs schedules Hard at `round((s0 + s1) / 2)`
 *    minutes (or `round(1.5 · s0)` with one step) at *every* step; py-fsrs uses the exact
 *    average at step 0 and repeats the current step afterwards.
 * 4. **Interval ordering in `Review`.** ts-fsrs forces `Hard < Good < Easy` on the day
 *    intervals of a reviewed card (Anki's convention); py-fsrs schedules each button on
 *    its own, so two buttons can share a day.
 * 5. **Rounding.** ts-fsrs rounds S, D and the curve constants to 8 decimals at every
 *    step; py-fsrs does not. Hence the 1e-6 tolerance on S and D.
 */

interface FixtureCard {
  state: 0 | 1 | 2 | 3
  step: number
  stability: number | null
  difficulty: number | null
  due: string
  lastReview: string | null
}

interface FixtureStep {
  review: string
  rating: Grade
  elapsedDays: number
  retrievabilityBefore: number
  before: FixtureCard
  after: FixtureCard & { dueOffsetMs: number; intervalDays: number | null }
}

interface FixtureConfig {
  w: number[]
  desiredRetention: number
  maxIntervalDays: number
  learningSteps: StepUnit[]
  relearningSteps: StepUnit[]
}

interface Fixture {
  generator: { pyFsrs: string; fuzz: boolean; seed: number; sequences: number }
  configs: Record<string, FixtureConfig>
  sequences: Array<{ id: string; config: string; steps: FixtureStep[] }>
}

const fixture = raw as unknown as Fixture

const RELATIVE_TOLERANCE = 1e-6
const MINUTE_MS = 60_000

function relativeError(actual: number, expected: number): number {
  return Math.abs(actual - expected) / Math.max(1, Math.abs(expected))
}

function optionsFor(config: FixtureConfig): SchedulingOptions {
  return {
    desiredRetention: config.desiredRetention,
    maxIntervalDays: config.maxIntervalDays,
    learningSteps: config.learningSteps,
    relearningSteps: config.relearningSteps,
    fuzz: false,
  }
}

/** ts-fsrs's minutes for a rating that stays inside the (re)learning steps. */
function tsFsrsStepMinutes(
  steps: readonly StepUnit[],
  currentStep: number,
  rating: Grade,
): number | null {
  const minutes = steps.map(stepUnitToMinutes)
  const first = minutes[0]
  if (first === undefined) return null
  switch (rating) {
    case 1:
      return first
    case 2:
      return minutes.length === 1
        ? Math.round(first * 1.5)
        : Math.round((first + (minutes[1] as number)) / 2)
    case 3:
      return minutes[currentStep + 1] ?? null
    default:
      return null
  }
}

const schedulers = new Map<string, FsrsScheduler>()
function schedulerFor(name: string): FsrsScheduler {
  let scheduler = schedulers.get(name)
  if (scheduler === undefined) {
    scheduler = createFsrsScheduler({ w: (fixture.configs[name] as FixtureConfig).w })
    schedulers.set(name, scheduler)
  }
  return scheduler
}

const discrepancies = { s0Clamp: 0, hardStep: 0, ordering: 0 }

describe('py-fsrs regression fixtures', () => {
  it('were generated by the pinned py-fsrs, with fuzz off', () => {
    expect(fixture.generator.pyFsrs).toBe('6.3.2')
    expect(fixture.generator.fuzz).toBe(false)
    expect(fixture.sequences.length).toBeGreaterThanOrEqual(200)
    const reviews = fixture.sequences.reduce((sum, seq) => sum + seq.steps.length, 0)
    expect(reviews).toBeGreaterThan(1000)
  })

  describe('every transition, from py-fsrs’s own state', () => {
    for (const sequence of fixture.sequences) {
      it(sequence.id, () => {
        const config = fixture.configs[sequence.config] as FixtureConfig
        const options = optionsFor(config)
        const scheduler = schedulerFor(sequence.config)
        const w20 = config.w[20] as number
        let reps = 0
        let lapses = 0
        let scheduledDays = 0

        for (const [index, step] of sequence.steps.entries()) {
          const where = `${sequence.id} step ${index}`
          const now = new Date(step.review)
          const card = cardFixture({
            id: sequence.id,
            state: step.before.state,
            learningSteps: step.before.step,
            stability: step.before.stability ?? 0,
            difficulty: step.before.difficulty ?? 0,
            due: new Date(step.before.due),
            lastReview: step.before.lastReview === null ? null : new Date(step.before.lastReview),
            reps,
            lapses,
            scheduledDays,
          })

          expect(
            Math.abs(scheduler.retrievability(card, now) - step.retrievabilityBefore),
            `${where} retrievability`,
          ).toBeLessThanOrEqual(1e-6)

          const result = scheduler.apply(card, now, step.rating, options)
          const { after } = step
          expect(result.log.elapsedDays, `${where} elapsedDays`).toBe(step.elapsedDays)
          expect(result.card.state, `${where} state`).toBe(after.state)
          expect(result.card.learningSteps, `${where} learning step`).toBe(after.step)

          // (1) The initial-stability floor.
          if (step.before.state === CARD_STATE.New && (after.stability as number) < 0.1) {
            discrepancies.s0Clamp += 1
            expect(result.card.stability, `${where} S0 floor`).toBe(0.1)
          } else {
            expect(
              relativeError(result.card.stability, after.stability as number),
              `${where} stability ${result.card.stability} vs ${after.stability}`,
            ).toBeLessThanOrEqual(RELATIVE_TOLERANCE)
          }
          expect(
            relativeError(result.card.difficulty, after.difficulty as number),
            `${where} difficulty`,
          ).toBeLessThanOrEqual(RELATIVE_TOLERANCE)

          const dueOffsetMs = result.card.due.getTime() - now.getTime()
          if (after.state === CARD_STATE.Review) {
            const expectedDays = after.intervalDays as number
            expect(dueOffsetMs, `${where} due is scheduledDays out`).toBe(
              result.card.scheduledDays * DAY_MS,
            )
            if (step.before.state === CARD_STATE.Review && step.rating !== 1) {
              // (4) Hard < Good < Easy, reconstructed from the closed form over the preview.
              const preview = scheduler.preview(card, now, options)
              const unconstrained = (grade: Grade) =>
                scheduledInterval(
                  options.desiredRetention,
                  preview[grade].card.stability,
                  options.maxIntervalDays,
                  w20,
                )
              expect(unconstrained(step.rating), `${where} closed-form interval`).toBe(expectedDays)
              const hard = Math.min(unconstrained(2), unconstrained(3))
              const good = Math.max(unconstrained(3), hard + 1)
              const easy = Math.max(unconstrained(4), good + 1)
              const ordered = { 2: hard, 3: good, 4: easy }[step.rating]
              if (ordered !== expectedDays) discrepancies.ordering += 1
              expect(result.card.scheduledDays, `${where} ordered interval`).toBe(ordered)
            } else {
              expect(result.card.scheduledDays, `${where} interval`).toBe(expectedDays)
            }
          } else {
            // A learning step: minutes. Compare with what ts-fsrs's step strategy books.
            const steps =
              step.before.state === CARD_STATE.Review || step.before.state === CARD_STATE.Relearning
                ? config.relearningSteps
                : config.learningSteps
            const minutes = tsFsrsStepMinutes(steps, step.before.step, step.rating)
            expect(minutes, `${where} a learning step must exist`).not.toBeNull()
            expect(dueOffsetMs, `${where} step minutes`).toBe((minutes as number) * MINUTE_MS)
            if (dueOffsetMs !== after.dueOffsetMs) {
              // (3) Only Hard may differ from py-fsrs, and only inside the steps.
              expect(step.rating, `${where} py-fsrs differs on a non-Hard step`).toBe(2)
              discrepancies.hardStep += 1
            }
          }

          // The log carries the card's own before-values.
          expect(result.log.state).toBe(step.before.state)
          expect(result.log.stability).toBe(step.before.stability ?? 0)
          expect(result.log.difficulty).toBe(step.before.difficulty ?? 0)
          expect(result.log.learningSteps).toBe(step.before.step)
          expect(result.log.review.getTime()).toBe(now.getTime())
          expect(result.log.algorithmVersion).toBe('fsrs6')

          reps += 1
          if (step.before.state === CARD_STATE.Review && step.rating === 1) lapses += 1
          scheduledDays = after.state === CARD_STATE.Review ? (after.intervalDays as number) : 0
        }
      })
    }
  })

  describe('whole sequences, chained through our own cards', () => {
    for (const sequence of fixture.sequences) {
      // (1) makes the trajectories diverge from the first review on; the transitions
      // above still check every step of those sequences individually.
      if (sequence.config === 's0-clamp') continue
      it(sequence.id, () => {
        const config = fixture.configs[sequence.config] as FixtureConfig
        const options = optionsFor(config)
        const scheduler = schedulerFor(sequence.config)
        const first = sequence.steps[0] as FixtureStep
        let card = cardFixture({ id: sequence.id, due: new Date(first.before.due) })
        for (const [index, step] of sequence.steps.entries()) {
          const where = `${sequence.id} step ${index}`
          card = scheduler.apply(card, new Date(step.review), step.rating, options).card
          expect(card.state, `${where} state`).toBe(step.after.state)
          expect(card.learningSteps, `${where} step`).toBe(step.after.step)
          expect(
            relativeError(card.stability, step.after.stability as number),
            `${where} stability`,
          ).toBeLessThanOrEqual(RELATIVE_TOLERANCE)
          expect(
            relativeError(card.difficulty, step.after.difficulty as number),
            `${where} difficulty`,
          ).toBeLessThanOrEqual(RELATIVE_TOLERANCE)
          expect(card.reps, `${where} reps`).toBe(index + 1)
        }
      })
    }
  })

  it('exercised every documented discrepancy at least once', () => {
    expect(discrepancies.s0Clamp).toBeGreaterThan(0)
    expect(discrepancies.hardStep).toBeGreaterThan(0)
    expect(discrepancies.ordering).toBeGreaterThan(0)
  })

  it('(2) masks the same-day increase for Hard, as ts-fsrs and py-fsrs ≥ 6.3.2 do', () => {
    // With a large S the raw increase S^(−w19)·e^(w17·(2−3+w18)) is below 1; masked, a
    // same-day Hard leaves S unchanged instead of shrinking it.
    const scheduler = schedulerFor('default')
    const now = new Date('2026-03-01T08:00:00Z')
    const card = cardFixture({
      state: 2,
      stability: 400,
      difficulty: 5,
      reps: 4,
      lastReview: new Date('2026-03-01T07:30:00Z'),
      due: new Date('2027-03-01T07:30:00Z'),
    })
    const result = scheduler.apply(
      card,
      now,
      2,
      optionsFor(fixture.configs.default as FixtureConfig),
    )
    expect(result.log.elapsedDays).toBe(0)
    expect(result.card.stability).toBe(400)
  })
})
