CREATE TABLE `exam_attempts` (
	`id` text PRIMARY KEY NOT NULL,
	`exam_id` text NOT NULL,
	`mode` text DEFAULT 'real' NOT NULL,
	`started_at` integer NOT NULL,
	`finished_at` integer,
	`score` real,
	`by_topic` text DEFAULT '{}' NOT NULL,
	`items` text DEFAULT '[]' NOT NULL,
	`readiness_predicted` real,
	`affects_scheduling` integer DEFAULT 1 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`exam_id`) REFERENCES `exams`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "exam_attempts_mode" CHECK("exam_attempts"."mode" IN ('real', 'blind', 'preview')),
	CONSTRAINT "exam_attempts_score_range" CHECK("exam_attempts"."score" IS NULL OR ("exam_attempts"."score" >= 0 AND "exam_attempts"."score" <= 1)),
	CONSTRAINT "exam_attempts_readiness_range" CHECK("exam_attempts"."readiness_predicted" IS NULL OR ("exam_attempts"."readiness_predicted" >= 0 AND "exam_attempts"."readiness_predicted" <= 1)),
	CONSTRAINT "exam_attempts_affects_scheduling_bool" CHECK("exam_attempts"."affects_scheduling" IN (0, 1)),
	CONSTRAINT "exam_attempts_finished_after_started" CHECK("exam_attempts"."finished_at" IS NULL OR "exam_attempts"."finished_at" >= "exam_attempts"."started_at"),
	CONSTRAINT "exam_attempts_by_topic_json" CHECK(json_valid("exam_attempts"."by_topic") AND json_type("exam_attempts"."by_topic") = 'object'),
	CONSTRAINT "exam_attempts_items_json" CHECK(json_valid("exam_attempts"."items") AND json_type("exam_attempts"."items") = 'array'),
	CONSTRAINT "exam_attempts_id_uuidv7" CHECK(length("exam_attempts"."id") = 36 AND substr("exam_attempts"."id", 15, 1) = '7'),
	CONSTRAINT "exam_attempts_version_positive" CHECK("exam_attempts"."version" >= 1),
	CONSTRAINT "exam_attempts_updated_after_created" CHECK("exam_attempts"."updated_at" >= "exam_attempts"."created_at")
);
--> statement-breakpoint
CREATE INDEX `exam_attempts_exam` ON `exam_attempts` (`exam_id`);--> statement-breakpoint
CREATE TABLE `exam_items` (
	`id` text PRIMARY KEY NOT NULL,
	`exam_id` text NOT NULL,
	`ordinal` integer NOT NULL,
	`activity_id` text NOT NULL,
	`item_bank_id` text,
	`form` text,
	`topic` text,
	`weight` real DEFAULT 1 NOT NULL,
	`time_limit_sec` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`exam_id`) REFERENCES `exams`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`activity_id`) REFERENCES `activities`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`item_bank_id`) REFERENCES `item_bank`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "exam_items_form" CHECK("exam_items"."form" IS NULL OR "exam_items"."form" IN ('A', 'B')),
	CONSTRAINT "exam_items_ordinal_nonnegative" CHECK("exam_items"."ordinal" >= 0),
	CONSTRAINT "exam_items_weight_nonnegative" CHECK("exam_items"."weight" >= 0),
	CONSTRAINT "exam_items_time_limit_positive" CHECK("exam_items"."time_limit_sec" IS NULL OR "exam_items"."time_limit_sec" >= 1),
	CONSTRAINT "exam_items_id_uuidv7" CHECK(length("exam_items"."id") = 36 AND substr("exam_items"."id", 15, 1) = '7'),
	CONSTRAINT "exam_items_version_positive" CHECK("exam_items"."version" >= 1),
	CONSTRAINT "exam_items_updated_after_created" CHECK("exam_items"."updated_at" >= "exam_items"."created_at")
);
--> statement-breakpoint
CREATE INDEX `exam_items_exam_ordinal` ON `exam_items` (`exam_id`,`ordinal`);--> statement-breakpoint
CREATE INDEX `exam_items_activity` ON `exam_items` (`activity_id`);--> statement-breakpoint
CREATE TABLE `exams` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`kind` text NOT NULL,
	`date` text,
	`path_id` text,
	`scope` text DEFAULT '{}' NOT NULL,
	`blueprint` text DEFAULT '[]' NOT NULL,
	`target_retention` real DEFAULT 0.95 NOT NULL,
	`final_window_days` integer DEFAULT 3 NOT NULL,
	`study_days_mask` integer DEFAULT 127 NOT NULL,
	`daily_capacity_minutes` integer,
	`status` text DEFAULT 'planned' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`path_id`) REFERENCES `paths`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "exams_kind" CHECK("exams"."kind" IN ('dated', 'mock', 'final', 'diagnostic')),
	CONSTRAINT "exams_status" CHECK("exams"."status" IN ('planned', 'active', 'completed', 'archived')),
	CONSTRAINT "exams_date_iso" CHECK("exams"."date" IS NULL OR "exams"."date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "exams_target_retention_range" CHECK("exams"."target_retention" >= 0.7 AND "exams"."target_retention" <= 0.99),
	CONSTRAINT "exams_final_window_nonnegative" CHECK("exams"."final_window_days" >= 0),
	CONSTRAINT "exams_study_days_mask_range" CHECK("exams"."study_days_mask" >= 0 AND "exams"."study_days_mask" <= 127),
	CONSTRAINT "exams_daily_capacity_positive" CHECK("exams"."daily_capacity_minutes" IS NULL OR "exams"."daily_capacity_minutes" >= 1),
	CONSTRAINT "exams_scope_json" CHECK(json_valid("exams"."scope") AND json_type("exams"."scope") = 'object'),
	CONSTRAINT "exams_blueprint_json" CHECK(json_valid("exams"."blueprint") AND json_type("exams"."blueprint") = 'array'),
	CONSTRAINT "exams_id_uuidv7" CHECK(length("exams"."id") = 36 AND substr("exams"."id", 15, 1) = '7'),
	CONSTRAINT "exams_version_positive" CHECK("exams"."version" >= 1),
	CONSTRAINT "exams_updated_after_created" CHECK("exams"."updated_at" >= "exams"."created_at")
);
--> statement-breakpoint
CREATE INDEX `exams_status_date` ON `exams` (`status`,`date`);--> statement-breakpoint
CREATE INDEX `exams_path` ON `exams` (`path_id`);--> statement-breakpoint
CREATE TABLE `item_bank` (
	`id` text PRIMARY KEY NOT NULL,
	`activity_id` text NOT NULL,
	`path_version_id` text,
	`module_id` text,
	`usage` text DEFAULT '[]' NOT NULL,
	`difficulty_logit` real DEFAULT 0 NOT NULL,
	`discrimination_hint` real,
	`exposure` integer DEFAULT 0 NOT NULL,
	`stats` text DEFAULT '{}' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`activity_id`) REFERENCES `activities`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`path_version_id`) REFERENCES `path_versions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`module_id`) REFERENCES `modules`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "item_bank_exposure_nonnegative" CHECK("item_bank"."exposure" >= 0),
	CONSTRAINT "item_bank_usage_json" CHECK(json_valid("item_bank"."usage") AND json_type("item_bank"."usage") = 'array'),
	CONSTRAINT "item_bank_stats_json" CHECK(json_valid("item_bank"."stats") AND json_type("item_bank"."stats") = 'object'),
	CONSTRAINT "item_bank_id_uuidv7" CHECK(length("item_bank"."id") = 36 AND substr("item_bank"."id", 15, 1) = '7'),
	CONSTRAINT "item_bank_version_positive" CHECK("item_bank"."version" >= 1),
	CONSTRAINT "item_bank_updated_after_created" CHECK("item_bank"."updated_at" >= "item_bank"."created_at")
);
--> statement-breakpoint
CREATE INDEX `item_bank_activity` ON `item_bank` (`activity_id`);--> statement-breakpoint
CREATE INDEX `item_bank_module` ON `item_bank` (`module_id`);--> statement-breakpoint
CREATE INDEX `item_bank_version` ON `item_bank` (`path_version_id`);--> statement-breakpoint
CREATE TABLE `achievements` (
	`id` text PRIMARY KEY NOT NULL,
	`key` text NOT NULL,
	`progress` real DEFAULT 0 NOT NULL,
	`target` real DEFAULT 1 NOT NULL,
	`unlocked_at` integer,
	`meta` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "achievements_key_nonempty" CHECK(length("achievements"."key") > 0),
	CONSTRAINT "achievements_progress_nonnegative" CHECK("achievements"."progress" >= 0),
	CONSTRAINT "achievements_target_positive" CHECK("achievements"."target" > 0),
	CONSTRAINT "achievements_meta_json" CHECK("achievements"."meta" IS NULL OR (json_valid("achievements"."meta") AND json_type("achievements"."meta") = 'object')),
	CONSTRAINT "achievements_id_uuidv7" CHECK(length("achievements"."id") = 36 AND substr("achievements"."id", 15, 1) = '7'),
	CONSTRAINT "achievements_version_positive" CHECK("achievements"."version" >= 1),
	CONSTRAINT "achievements_updated_after_created" CHECK("achievements"."updated_at" >= "achievements"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `achievements_key_live` ON `achievements` (`key`) WHERE "achievements"."deleted_at" IS NULL;--> statement-breakpoint
CREATE TABLE `streaks` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`current_length` integer DEFAULT 0 NOT NULL,
	`longest_length` integer DEFAULT 0 NOT NULL,
	`goal` integer DEFAULT 10 NOT NULL,
	`last_active_day` text,
	`started_on` text,
	`freezes_available` integer DEFAULT 0 NOT NULL,
	`freezes_used` integer DEFAULT 0 NOT NULL,
	`freeze_bank_max` integer DEFAULT 2 NOT NULL,
	`holidays` text DEFAULT '[]' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "streaks_current_nonnegative" CHECK("streaks"."current_length" >= 0),
	CONSTRAINT "streaks_longest_nonnegative" CHECK("streaks"."longest_length" >= 0),
	CONSTRAINT "streaks_goal_positive" CHECK("streaks"."goal" >= 1),
	CONSTRAINT "streaks_freezes_range" CHECK("streaks"."freezes_available" >= 0 AND "streaks"."freezes_available" <= 1000),
	CONSTRAINT "streaks_freezes_used_nonnegative" CHECK("streaks"."freezes_used" >= 0),
	CONSTRAINT "streaks_freeze_bank_nonnegative" CHECK("streaks"."freeze_bank_max" >= 0),
	CONSTRAINT "streaks_holidays_json" CHECK(json_valid("streaks"."holidays") AND json_type("streaks"."holidays") = 'array'),
	CONSTRAINT "streaks_id_uuidv7" CHECK(length("streaks"."id") = 36 AND substr("streaks"."id", 15, 1) = '7'),
	CONSTRAINT "streaks_version_positive" CHECK("streaks"."version" >= 1),
	CONSTRAINT "streaks_updated_after_created" CHECK("streaks"."updated_at" >= "streaks"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `streaks_kind_live` ON `streaks` (`kind`) WHERE "streaks"."deleted_at" IS NULL;--> statement-breakpoint
CREATE TABLE `xp_events` (
	`id` text PRIMARY KEY NOT NULL,
	`amount` integer NOT NULL,
	`reason` text NOT NULL,
	`subject_kind` text,
	`subject_id` text,
	`occurred_at` integer NOT NULL,
	`multiplier` real DEFAULT 1 NOT NULL,
	`meta` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "xp_events_reason" CHECK("xp_events"."reason" IN ('lesson', 'review', 'reinforcement', 'mock_exam', 'quest', 'achievement', 'bonus')),
	CONSTRAINT "xp_events_amount_nonnegative" CHECK("xp_events"."amount" >= 0),
	CONSTRAINT "xp_events_multiplier_positive" CHECK("xp_events"."multiplier" > 0),
	CONSTRAINT "xp_events_meta_json" CHECK("xp_events"."meta" IS NULL OR (json_valid("xp_events"."meta") AND json_type("xp_events"."meta") = 'object')),
	CONSTRAINT "xp_events_id_uuidv7" CHECK(length("xp_events"."id") = 36 AND substr("xp_events"."id", 15, 1) = '7'),
	CONSTRAINT "xp_events_version_positive" CHECK("xp_events"."version" >= 1),
	CONSTRAINT "xp_events_updated_after_created" CHECK("xp_events"."updated_at" >= "xp_events"."created_at")
);
--> statement-breakpoint
CREATE INDEX `xp_events_occurred` ON `xp_events` (`occurred_at`);--> statement-breakpoint
CREATE INDEX `xp_events_subject` ON `xp_events` (`subject_kind`,`subject_id`);--> statement-breakpoint
CREATE TABLE `annotations` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`unit_id` text,
	`kind` text NOT NULL,
	`anchor` text NOT NULL,
	`quote` text,
	`note` text,
	`color` text,
	`t_start` real,
	`t_end` real,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `sources`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`unit_id`) REFERENCES `source_units`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "annotations_kind" CHECK("annotations"."kind" IN ('highlight', 'note', 'region', 'clip')),
	CONSTRAINT "annotations_anchor_json" CHECK(json_valid("annotations"."anchor") AND json_type("annotations"."anchor") = 'object'),
	CONSTRAINT "annotations_time_range" CHECK("annotations"."t_start" IS NULL OR "annotations"."t_end" IS NULL OR "annotations"."t_end" >= "annotations"."t_start"),
	CONSTRAINT "annotations_t_start_nonnegative" CHECK("annotations"."t_start" IS NULL OR ("annotations"."t_start" >= 0 AND "annotations"."t_start" <= 9007199254740991)),
	CONSTRAINT "annotations_id_uuidv7" CHECK(length("annotations"."id") = 36 AND substr("annotations"."id", 15, 1) = '7'),
	CONSTRAINT "annotations_version_positive" CHECK("annotations"."version" >= 1),
	CONSTRAINT "annotations_updated_after_created" CHECK("annotations"."updated_at" >= "annotations"."created_at")
);
--> statement-breakpoint
CREATE INDEX `annotations_source` ON `annotations` (`source_id`);--> statement-breakpoint
CREATE INDEX `annotations_unit` ON `annotations` (`unit_id`);--> statement-breakpoint
CREATE TABLE `blobs` (
	`id` text PRIMARY KEY NOT NULL,
	`sha256` text NOT NULL,
	`mime` text NOT NULL,
	`bytes` integer NOT NULL,
	`ext` text,
	`original_name` text,
	`meta` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "blobs_sha256_hex" CHECK(length("blobs"."sha256") = 64 AND "blobs"."sha256" = lower("blobs"."sha256")),
	CONSTRAINT "blobs_bytes_nonnegative" CHECK("blobs"."bytes" >= 0),
	CONSTRAINT "blobs_meta_json" CHECK("blobs"."meta" IS NULL OR (json_valid("blobs"."meta") AND json_type("blobs"."meta") = 'object')),
	CONSTRAINT "blobs_id_uuidv7" CHECK(length("blobs"."id") = 36 AND substr("blobs"."id", 15, 1) = '7'),
	CONSTRAINT "blobs_version_positive" CHECK("blobs"."version" >= 1),
	CONSTRAINT "blobs_updated_after_created" CHECK("blobs"."updated_at" >= "blobs"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `blobs_sha256` ON `blobs` (`sha256`);--> statement-breakpoint
CREATE TABLE `chunks` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`unit_id` text,
	`ordinal` integer NOT NULL,
	`text` text NOT NULL,
	`char_start` integer NOT NULL,
	`char_end` integer NOT NULL,
	`token_count` integer NOT NULL,
	`hash` text NOT NULL,
	`heading_path` text,
	`context` text,
	`locator` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `sources`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`unit_id`) REFERENCES `source_units`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "chunks_char_range" CHECK("chunks"."char_start" >= 0 AND "chunks"."char_end" >= "chunks"."char_start"),
	CONSTRAINT "chunks_token_count_nonnegative" CHECK("chunks"."token_count" >= 0),
	CONSTRAINT "chunks_hash_hex" CHECK(length("chunks"."hash") = 64),
	CONSTRAINT "chunks_locator_json" CHECK("chunks"."locator" IS NULL OR (json_valid("chunks"."locator") AND json_type("chunks"."locator") = 'object')),
	CONSTRAINT "chunks_id_uuidv7" CHECK(length("chunks"."id") = 36 AND substr("chunks"."id", 15, 1) = '7'),
	CONSTRAINT "chunks_version_positive" CHECK("chunks"."version" >= 1),
	CONSTRAINT "chunks_updated_after_created" CHECK("chunks"."updated_at" >= "chunks"."created_at")
);
--> statement-breakpoint
CREATE INDEX `chunks_source_ordinal` ON `chunks` (`source_id`,`ordinal`);--> statement-breakpoint
CREATE INDEX `chunks_hash` ON `chunks` (`hash`);--> statement-breakpoint
CREATE INDEX `chunks_unit` ON `chunks` (`unit_id`);--> statement-breakpoint
CREATE TABLE `source_units` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`kind` text NOT NULL,
	`ordinal` integer NOT NULL,
	`label` text,
	`t_start` integer,
	`t_end` integer,
	`text` text,
	`blob_sha256` text,
	`meta` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `sources`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`blob_sha256`) REFERENCES `blobs`(`sha256`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "source_units_kind" CHECK("source_units"."kind" IN ('page', 'slide', 'section', 'keyframe', 'segment')),
	CONSTRAINT "source_units_ordinal_nonnegative" CHECK("source_units"."ordinal" >= 0),
	CONSTRAINT "source_units_time_range" CHECK("source_units"."t_start" IS NULL OR "source_units"."t_end" IS NULL OR "source_units"."t_end" >= "source_units"."t_start"),
	CONSTRAINT "source_units_meta_json" CHECK("source_units"."meta" IS NULL OR (json_valid("source_units"."meta") AND json_type("source_units"."meta") = 'object')),
	CONSTRAINT "source_units_id_uuidv7" CHECK(length("source_units"."id") = 36 AND substr("source_units"."id", 15, 1) = '7'),
	CONSTRAINT "source_units_version_positive" CHECK("source_units"."version" >= 1),
	CONSTRAINT "source_units_updated_after_created" CHECK("source_units"."updated_at" >= "source_units"."created_at")
);
--> statement-breakpoint
CREATE INDEX `source_units_source_ordinal` ON `source_units` (`source_id`,`ordinal`);--> statement-breakpoint
CREATE TABLE `sources` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`title` text NOT NULL,
	`origin_uri` text,
	`blob_sha256` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`language` text,
	`meta` text,
	`error` text,
	`ingested_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`blob_sha256`) REFERENCES `blobs`(`sha256`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "sources_kind" CHECK("sources"."kind" IN ('pdf', 'docx', 'epub', 'pptx', 'markdown', 'text', 'image', 'audio', 'video', 'youtube', 'web')),
	CONSTRAINT "sources_status" CHECK("sources"."status" IN ('pending', 'processing', 'ready', 'failed')),
	CONSTRAINT "sources_meta_json" CHECK("sources"."meta" IS NULL OR (json_valid("sources"."meta") AND json_type("sources"."meta") = 'object')),
	CONSTRAINT "sources_id_uuidv7" CHECK(length("sources"."id") = 36 AND substr("sources"."id", 15, 1) = '7'),
	CONSTRAINT "sources_version_positive" CHECK("sources"."version" >= 1),
	CONSTRAINT "sources_updated_after_created" CHECK("sources"."updated_at" >= "sources"."created_at")
);
--> statement-breakpoint
CREATE INDEX `sources_status` ON `sources` (`status`);--> statement-breakpoint
CREATE INDEX `sources_blob` ON `sources` (`blob_sha256`);--> statement-breakpoint
CREATE TABLE `cards` (
	`id` text PRIMARY KEY NOT NULL,
	`item_id` text NOT NULL,
	`template` text NOT NULL,
	`payload` text,
	`due` integer NOT NULL,
	`stability` real DEFAULT 0 NOT NULL,
	`difficulty` real DEFAULT 0 NOT NULL,
	`scheduled_days` integer DEFAULT 0 NOT NULL,
	`learning_steps` integer DEFAULT 0 NOT NULL,
	`reps` integer DEFAULT 0 NOT NULL,
	`lapses` integer DEFAULT 0 NOT NULL,
	`state` integer DEFAULT 0 NOT NULL,
	`last_review` integer,
	`suspended` integer DEFAULT 0 NOT NULL,
	`buried_until` integer,
	`leech` integer DEFAULT 0 NOT NULL,
	`importance_override` text,
	`exam_id` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`item_id`) REFERENCES `knowledge_items`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`exam_id`) REFERENCES `exams`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "cards_state" CHECK("cards"."state" IN (0, 1, 2, 3)),
	CONSTRAINT "cards_suspended_bool" CHECK("cards"."suspended" IN (0, 1)),
	CONSTRAINT "cards_leech_bool" CHECK("cards"."leech" IN (0, 1)),
	CONSTRAINT "cards_importance_override" CHECK("cards"."importance_override" IS NULL OR "cards"."importance_override" IN ('urgent', 'high', 'normal', 'maintenance', 'paused')),
	CONSTRAINT "cards_stability_nonnegative" CHECK("cards"."stability" >= 0),
	CONSTRAINT "cards_difficulty_range" CHECK("cards"."difficulty" >= 0 AND "cards"."difficulty" <= 10),
	CONSTRAINT "cards_scheduled_days_nonnegative" CHECK("cards"."scheduled_days" >= 0),
	CONSTRAINT "cards_learning_steps_nonnegative" CHECK("cards"."learning_steps" >= 0),
	CONSTRAINT "cards_reps_nonnegative" CHECK("cards"."reps" >= 0),
	CONSTRAINT "cards_lapses_nonnegative" CHECK("cards"."lapses" >= 0),
	CONSTRAINT "cards_payload_json" CHECK("cards"."payload" IS NULL OR (json_valid("cards"."payload") AND json_type("cards"."payload") = 'object')),
	CONSTRAINT "cards_id_uuidv7" CHECK(length("cards"."id") = 36 AND substr("cards"."id", 15, 1) = '7'),
	CONSTRAINT "cards_version_positive" CHECK("cards"."version" >= 1),
	CONSTRAINT "cards_updated_after_created" CHECK("cards"."updated_at" >= "cards"."created_at")
);
--> statement-breakpoint
CREATE INDEX `cards_due` ON `cards` (`due`) WHERE "cards"."suspended" = 0 AND "cards"."deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX `cards_item` ON `cards` (`item_id`);--> statement-breakpoint
CREATE INDEX `cards_exam` ON `cards` (`exam_id`);--> statement-breakpoint
CREATE INDEX `cards_state` ON `cards` (`state`);--> statement-breakpoint
CREATE UNIQUE INDEX `cards_item_template_live` ON `cards` (`item_id`,`template`) WHERE "cards"."deleted_at" IS NULL;--> statement-breakpoint
CREATE TABLE `importance_levels` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`desired_retention` real,
	`max_interval_days` integer,
	`order_rank` integer NOT NULL,
	`postpone_allowed` integer NOT NULL,
	`new_per_day` integer,
	`leech_threshold` integer DEFAULT 8 NOT NULL,
	`leech_action` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "importance_levels_name" CHECK("importance_levels"."name" IN ('urgent', 'high', 'normal', 'maintenance', 'paused')),
	CONSTRAINT "importance_levels_desired_retention_range" CHECK("importance_levels"."desired_retention" IS NULL OR ("importance_levels"."desired_retention" >= 0.7 AND "importance_levels"."desired_retention" <= 0.99)),
	CONSTRAINT "importance_levels_max_interval_positive" CHECK("importance_levels"."max_interval_days" IS NULL OR "importance_levels"."max_interval_days" >= 1),
	CONSTRAINT "importance_levels_order_rank_positive" CHECK("importance_levels"."order_rank" >= 1),
	CONSTRAINT "importance_levels_postpone_allowed_bool" CHECK("importance_levels"."postpone_allowed" IN (0, 1)),
	CONSTRAINT "importance_levels_new_per_day_nonnegative" CHECK("importance_levels"."new_per_day" IS NULL OR "importance_levels"."new_per_day" >= 0),
	CONSTRAINT "importance_levels_leech_threshold_positive" CHECK("importance_levels"."leech_threshold" >= 1),
	CONSTRAINT "importance_levels_leech_action" CHECK("importance_levels"."leech_action" IN ('warn', 'warn_rewrite', 'edit', 'suspend', 'none')),
	CONSTRAINT "importance_levels_id_uuidv7" CHECK(length("importance_levels"."id") = 36 AND substr("importance_levels"."id", 15, 1) = '7'),
	CONSTRAINT "importance_levels_version_positive" CHECK("importance_levels"."version" >= 1),
	CONSTRAINT "importance_levels_updated_after_created" CHECK("importance_levels"."updated_at" >= "importance_levels"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `importance_levels_name` ON `importance_levels` (`name`);--> statement-breakpoint
CREATE TABLE `knowledge_items` (
	`id` text PRIMARY KEY NOT NULL,
	`lesson_id` text,
	`topic_id` text,
	`kind` text NOT NULL,
	`fields` text NOT NULL,
	`source_id` text,
	`annotation_id` text,
	`locator` text,
	`as_of` text,
	`importance` text DEFAULT 'normal' NOT NULL,
	`status` text DEFAULT 'need_to_learn' NOT NULL,
	`created_by` text DEFAULT 'user' NOT NULL,
	`tags` text DEFAULT '[]' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`lesson_id`) REFERENCES `lessons`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`source_id`) REFERENCES `sources`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`annotation_id`) REFERENCES `annotations`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "knowledge_items_kind" CHECK("knowledge_items"."kind" IN ('fact', 'concept', 'procedure', 'principle', 'example', 'misconception', 'vocabulary', 'other')),
	CONSTRAINT "knowledge_items_importance" CHECK("knowledge_items"."importance" IN ('urgent', 'high', 'normal', 'maintenance', 'paused')),
	CONSTRAINT "knowledge_items_status" CHECK("knowledge_items"."status" IN ('need_to_learn', 'active', 'archived')),
	CONSTRAINT "knowledge_items_created_by" CHECK("knowledge_items"."created_by" IN ('user', 'ai', 'import')),
	CONSTRAINT "knowledge_items_fields_json" CHECK(json_valid("knowledge_items"."fields") AND json_type("knowledge_items"."fields") = 'object'),
	CONSTRAINT "knowledge_items_locator_json" CHECK("knowledge_items"."locator" IS NULL OR (json_valid("knowledge_items"."locator") AND json_type("knowledge_items"."locator") = 'object')),
	CONSTRAINT "knowledge_items_tags_json" CHECK(json_valid("knowledge_items"."tags") AND json_type("knowledge_items"."tags") = 'array'),
	CONSTRAINT "knowledge_items_id_uuidv7" CHECK(length("knowledge_items"."id") = 36 AND substr("knowledge_items"."id", 15, 1) = '7'),
	CONSTRAINT "knowledge_items_version_positive" CHECK("knowledge_items"."version" >= 1),
	CONSTRAINT "knowledge_items_updated_after_created" CHECK("knowledge_items"."updated_at" >= "knowledge_items"."created_at")
);
--> statement-breakpoint
CREATE INDEX `knowledge_items_lesson` ON `knowledge_items` (`lesson_id`);--> statement-breakpoint
CREATE INDEX `knowledge_items_source` ON `knowledge_items` (`source_id`);--> statement-breakpoint
CREATE INDEX `knowledge_items_annotation` ON `knowledge_items` (`annotation_id`);--> statement-breakpoint
CREATE INDEX `knowledge_items_topic` ON `knowledge_items` (`topic_id`);--> statement-breakpoint
CREATE INDEX `knowledge_items_status_importance` ON `knowledge_items` (`status`,`importance`);--> statement-breakpoint
CREATE TABLE `scheduler_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`scope` text NOT NULL,
	`algorithm` text DEFAULT 'fsrs6' NOT NULL,
	`w` text NOT NULL,
	`decay` real,
	`learning_steps` text DEFAULT '["1m","10m"]' NOT NULL,
	`relearning_steps` text DEFAULT '["10m"]' NOT NULL,
	`enable_fuzz` integer DEFAULT 1 NOT NULL,
	`enable_short_term` integer DEFAULT 1 NOT NULL,
	`maximum_interval` integer DEFAULT 36500 NOT NULL,
	`day_start_hour` integer DEFAULT 4 NOT NULL,
	`trained_at` integer,
	`n_reviews` integer,
	`log_loss` real,
	`rmse` real,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "scheduler_profiles_w_json" CHECK(json_valid("scheduler_profiles"."w") AND json_type("scheduler_profiles"."w") = 'array'),
	CONSTRAINT "scheduler_profiles_learning_steps_json" CHECK(json_valid("scheduler_profiles"."learning_steps") AND json_type("scheduler_profiles"."learning_steps") = 'array'),
	CONSTRAINT "scheduler_profiles_relearning_steps_json" CHECK(json_valid("scheduler_profiles"."relearning_steps") AND json_type("scheduler_profiles"."relearning_steps") = 'array'),
	CONSTRAINT "scheduler_profiles_enable_fuzz_bool" CHECK("scheduler_profiles"."enable_fuzz" IN (0, 1)),
	CONSTRAINT "scheduler_profiles_enable_short_term_bool" CHECK("scheduler_profiles"."enable_short_term" IN (0, 1)),
	CONSTRAINT "scheduler_profiles_maximum_interval_positive" CHECK("scheduler_profiles"."maximum_interval" >= 1),
	CONSTRAINT "scheduler_profiles_day_start_hour_range" CHECK("scheduler_profiles"."day_start_hour" >= 0 AND "scheduler_profiles"."day_start_hour" <= 23),
	CONSTRAINT "scheduler_profiles_n_reviews_nonnegative" CHECK("scheduler_profiles"."n_reviews" IS NULL OR "scheduler_profiles"."n_reviews" >= 0),
	CONSTRAINT "scheduler_profiles_id_uuidv7" CHECK(length("scheduler_profiles"."id") = 36 AND substr("scheduler_profiles"."id", 15, 1) = '7'),
	CONSTRAINT "scheduler_profiles_version_positive" CHECK("scheduler_profiles"."version" >= 1),
	CONSTRAINT "scheduler_profiles_updated_after_created" CHECK("scheduler_profiles"."updated_at" >= "scheduler_profiles"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `scheduler_profiles_scope_live` ON `scheduler_profiles` (`scope`) WHERE "scheduler_profiles"."deleted_at" IS NULL;--> statement-breakpoint
CREATE TABLE `activities` (
	`id` text PRIMARY KEY NOT NULL,
	`lesson_id` text,
	`ordinal` integer,
	`type` text NOT NULL,
	`family` text NOT NULL,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`lang` text NOT NULL,
	`bloom` text,
	`difficulty` integer,
	`concept_ids` text DEFAULT '[]' NOT NULL,
	`misconception_ids` text DEFAULT '[]' NOT NULL,
	`config` text NOT NULL,
	`grading` text NOT NULL,
	`status` text DEFAULT 'ready' NOT NULL,
	`source_refs` text DEFAULT '[]' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`lesson_id`) REFERENCES `lessons`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "activities_family" CHECK("activities"."family" IN ('choice', 'text_input', 'cloze', 'long_text', 'pairs', 'ordering', 'categorize', 'image_target', 'text_mark', 'scale', 'speech', 'dialogue', 'branching', 'media_checkpoints', 'code', 'math', 'graph', 'grid_game', 'arcade', 'cards', 'disclosure', 'draw', 'simulation')),
	CONSTRAINT "activities_status" CHECK("activities"."status" IN ('ready', 'pending_media', 'needs_review', 'rejected')),
	CONSTRAINT "activities_bloom" CHECK("activities"."bloom" IS NULL OR "activities"."bloom" IN ('remember', 'understand', 'apply', 'analyze', 'evaluate', 'create')),
	CONSTRAINT "activities_difficulty_range" CHECK("activities"."difficulty" IS NULL OR ("activities"."difficulty" >= 1 AND "activities"."difficulty" <= 5)),
	CONSTRAINT "activities_schema_version_positive" CHECK("activities"."schema_version" >= 1),
	CONSTRAINT "activities_ordinal_nonnegative" CHECK("activities"."ordinal" IS NULL OR "activities"."ordinal" >= 0),
	CONSTRAINT "activities_concept_ids_json" CHECK(json_valid("activities"."concept_ids") AND json_type("activities"."concept_ids") = 'array'),
	CONSTRAINT "activities_misconception_ids_json" CHECK(json_valid("activities"."misconception_ids") AND json_type("activities"."misconception_ids") = 'array'),
	CONSTRAINT "activities_config_json" CHECK(json_valid("activities"."config") AND json_type("activities"."config") = 'object'),
	CONSTRAINT "activities_grading_json" CHECK(json_valid("activities"."grading") AND json_type("activities"."grading") = 'object'),
	CONSTRAINT "activities_source_refs_json" CHECK(json_valid("activities"."source_refs") AND json_type("activities"."source_refs") = 'array'),
	CONSTRAINT "activities_id_uuidv7" CHECK(length("activities"."id") = 36 AND substr("activities"."id", 15, 1) = '7'),
	CONSTRAINT "activities_version_positive" CHECK("activities"."version" >= 1),
	CONSTRAINT "activities_updated_after_created" CHECK("activities"."updated_at" >= "activities"."created_at")
);
--> statement-breakpoint
CREATE INDEX `activities_lesson_ordinal` ON `activities` (`lesson_id`,`ordinal`);--> statement-breakpoint
CREATE INDEX `activities_type` ON `activities` (`type`);--> statement-breakpoint
CREATE INDEX `activities_status` ON `activities` (`status`);--> statement-breakpoint
CREATE TABLE `lessons` (
	`id` text PRIMARY KEY NOT NULL,
	`module_id` text NOT NULL,
	`ordinal` integer NOT NULL,
	`spec_id` text NOT NULL,
	`kind` text DEFAULT 'core' NOT NULL,
	`parent_lesson_id` text,
	`title` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`objectives` text DEFAULT '[]' NOT NULL,
	`concept_ids` text DEFAULT '[]' NOT NULL,
	`prerequisite_lesson_ids` text DEFAULT '[]' NOT NULL,
	`estimated_minutes` integer,
	`theory` text,
	`citations` text DEFAULT '[]' NOT NULL,
	`qa` text,
	`remediation` text,
	`unlock_rule` text,
	`xp_reward` integer DEFAULT 0 NOT NULL,
	`completed_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`module_id`) REFERENCES `modules`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`parent_lesson_id`) REFERENCES `lessons`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "lessons_kind" CHECK("lessons"."kind" IN ('core', 'remediation', 'reinforcement', 'checkpoint')),
	CONSTRAINT "lessons_status" CHECK("lessons"."status" IN ('pending', 'generating', 'ready', 'failed')),
	CONSTRAINT "lessons_ordinal_nonnegative" CHECK("lessons"."ordinal" >= 0),
	CONSTRAINT "lessons_estimated_minutes_positive" CHECK("lessons"."estimated_minutes" IS NULL OR "lessons"."estimated_minutes" >= 0),
	CONSTRAINT "lessons_xp_nonnegative" CHECK("lessons"."xp_reward" >= 0),
	CONSTRAINT "lessons_objectives_json" CHECK(json_valid("lessons"."objectives") AND json_type("lessons"."objectives") = 'array'),
	CONSTRAINT "lessons_concept_ids_json" CHECK(json_valid("lessons"."concept_ids") AND json_type("lessons"."concept_ids") = 'array'),
	CONSTRAINT "lessons_prerequisites_json" CHECK(json_valid("lessons"."prerequisite_lesson_ids") AND json_type("lessons"."prerequisite_lesson_ids") = 'array'),
	CONSTRAINT "lessons_theory_json" CHECK("lessons"."theory" IS NULL OR (json_valid("lessons"."theory") AND json_type("lessons"."theory") = 'object')),
	CONSTRAINT "lessons_citations_json" CHECK(json_valid("lessons"."citations") AND json_type("lessons"."citations") = 'array'),
	CONSTRAINT "lessons_qa_json" CHECK("lessons"."qa" IS NULL OR (json_valid("lessons"."qa") AND json_type("lessons"."qa") = 'object')),
	CONSTRAINT "lessons_remediation_json" CHECK("lessons"."remediation" IS NULL OR (json_valid("lessons"."remediation") AND json_type("lessons"."remediation") = 'object')),
	CONSTRAINT "lessons_unlock_rule_json" CHECK("lessons"."unlock_rule" IS NULL OR (json_valid("lessons"."unlock_rule") AND json_type("lessons"."unlock_rule") = 'object')),
	CONSTRAINT "lessons_id_uuidv7" CHECK(length("lessons"."id") = 36 AND substr("lessons"."id", 15, 1) = '7'),
	CONSTRAINT "lessons_version_positive" CHECK("lessons"."version" >= 1),
	CONSTRAINT "lessons_updated_after_created" CHECK("lessons"."updated_at" >= "lessons"."created_at")
);
--> statement-breakpoint
CREATE INDEX `lessons_module_ordinal` ON `lessons` (`module_id`,`ordinal`);--> statement-breakpoint
CREATE INDEX `lessons_parent` ON `lessons` (`parent_lesson_id`);--> statement-breakpoint
CREATE INDEX `lessons_status` ON `lessons` (`status`);--> statement-breakpoint
CREATE TABLE `modules` (
	`id` text PRIMARY KEY NOT NULL,
	`section_id` text NOT NULL,
	`ordinal` integer NOT NULL,
	`spec_id` text NOT NULL,
	`title` text NOT NULL,
	`objectives` text DEFAULT '[]' NOT NULL,
	`diagnostic_item_ids` text DEFAULT '[]' NOT NULL,
	`unlock_rule` text,
	`xp_reward` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "modules_ordinal_nonnegative" CHECK("modules"."ordinal" >= 0),
	CONSTRAINT "modules_xp_nonnegative" CHECK("modules"."xp_reward" >= 0),
	CONSTRAINT "modules_objectives_json" CHECK(json_valid("modules"."objectives") AND json_type("modules"."objectives") = 'array'),
	CONSTRAINT "modules_diagnostic_item_ids_json" CHECK(json_valid("modules"."diagnostic_item_ids") AND json_type("modules"."diagnostic_item_ids") = 'array'),
	CONSTRAINT "modules_unlock_rule_json" CHECK("modules"."unlock_rule" IS NULL OR (json_valid("modules"."unlock_rule") AND json_type("modules"."unlock_rule") = 'object')),
	CONSTRAINT "modules_id_uuidv7" CHECK(length("modules"."id") = 36 AND substr("modules"."id", 15, 1) = '7'),
	CONSTRAINT "modules_version_positive" CHECK("modules"."version" >= 1),
	CONSTRAINT "modules_updated_after_created" CHECK("modules"."updated_at" >= "modules"."created_at")
);
--> statement-breakpoint
CREATE INDEX `modules_section_ordinal` ON `modules` (`section_id`,`ordinal`);--> statement-breakpoint
CREATE TABLE `path_versions` (
	`id` text PRIMARY KEY NOT NULL,
	`path_id` text NOT NULL,
	`number` integer NOT NULL,
	`spec` text NOT NULL,
	`knowledge_graph` text,
	`manifest` text,
	`diff` text,
	`frozen_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`path_id`) REFERENCES `paths`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "path_versions_number_positive" CHECK("path_versions"."number" >= 1),
	CONSTRAINT "path_versions_spec_json" CHECK(json_valid("path_versions"."spec") AND json_type("path_versions"."spec") = 'object'),
	CONSTRAINT "path_versions_knowledge_graph_json" CHECK("path_versions"."knowledge_graph" IS NULL OR (json_valid("path_versions"."knowledge_graph") AND json_type("path_versions"."knowledge_graph") = 'object')),
	CONSTRAINT "path_versions_manifest_json" CHECK("path_versions"."manifest" IS NULL OR (json_valid("path_versions"."manifest") AND json_type("path_versions"."manifest") = 'object')),
	CONSTRAINT "path_versions_diff_json" CHECK("path_versions"."diff" IS NULL OR (json_valid("path_versions"."diff") AND json_type("path_versions"."diff") = 'object')),
	CONSTRAINT "path_versions_id_uuidv7" CHECK(length("path_versions"."id") = 36 AND substr("path_versions"."id", 15, 1) = '7'),
	CONSTRAINT "path_versions_version_positive" CHECK("path_versions"."version" >= 1),
	CONSTRAINT "path_versions_updated_after_created" CHECK("path_versions"."updated_at" >= "path_versions"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `path_versions_path_number` ON `path_versions` (`path_id`,`number`);--> statement-breakpoint
CREATE TABLE `paths` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`language` text NOT NULL,
	`level` text,
	`goal` text,
	`target_date` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`active_version` integer,
	`source_ids` text DEFAULT '[]' NOT NULL,
	`settings` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "paths_status" CHECK("paths"."status" IN ('draft', 'generating', 'active', 'completed', 'archived')),
	CONSTRAINT "paths_active_version_positive" CHECK("paths"."active_version" IS NULL OR "paths"."active_version" >= 1),
	CONSTRAINT "paths_target_date_iso" CHECK("paths"."target_date" IS NULL OR "paths"."target_date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "paths_source_ids_json" CHECK(json_valid("paths"."source_ids") AND json_type("paths"."source_ids") = 'array'),
	CONSTRAINT "paths_settings_json" CHECK("paths"."settings" IS NULL OR (json_valid("paths"."settings") AND json_type("paths"."settings") = 'object')),
	CONSTRAINT "paths_id_uuidv7" CHECK(length("paths"."id") = 36 AND substr("paths"."id", 15, 1) = '7'),
	CONSTRAINT "paths_version_positive" CHECK("paths"."version" >= 1),
	CONSTRAINT "paths_updated_after_created" CHECK("paths"."updated_at" >= "paths"."created_at")
);
--> statement-breakpoint
CREATE INDEX `paths_status` ON `paths` (`status`);--> statement-breakpoint
CREATE TABLE `sections` (
	`id` text PRIMARY KEY NOT NULL,
	`path_version_id` text NOT NULL,
	`ordinal` integer NOT NULL,
	`spec_id` text NOT NULL,
	`title` text NOT NULL,
	`unlock_rule` text,
	`xp_reward` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`path_version_id`) REFERENCES `path_versions`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "sections_ordinal_nonnegative" CHECK("sections"."ordinal" >= 0),
	CONSTRAINT "sections_xp_nonnegative" CHECK("sections"."xp_reward" >= 0),
	CONSTRAINT "sections_unlock_rule_json" CHECK("sections"."unlock_rule" IS NULL OR (json_valid("sections"."unlock_rule") AND json_type("sections"."unlock_rule") = 'object')),
	CONSTRAINT "sections_id_uuidv7" CHECK(length("sections"."id") = 36 AND substr("sections"."id", 15, 1) = '7'),
	CONSTRAINT "sections_version_positive" CHECK("sections"."version" >= 1),
	CONSTRAINT "sections_updated_after_created" CHECK("sections"."updated_at" >= "sections"."created_at")
);
--> statement-breakpoint
CREATE INDEX `sections_version_ordinal` ON `sections` (`path_version_id`,`ordinal`);--> statement-breakpoint
CREATE TABLE `attempts` (
	`id` text PRIMARY KEY NOT NULL,
	`activity_id` text NOT NULL,
	`context` text NOT NULL,
	`lesson_session_id` text,
	`exam_attempt_id` text,
	`card_id` text,
	`started_at` integer NOT NULL,
	`finished_at` integer,
	`score` real,
	`correct` integer,
	`rating` integer,
	`answer` text,
	`feedback` text,
	`time_ms` integer,
	`tries` integer DEFAULT 1 NOT NULL,
	`hints_used` integer DEFAULT 0 NOT NULL,
	`confidence` text,
	`ai_eval_call_id` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`activity_id`) REFERENCES `activities`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lesson_session_id`) REFERENCES `lesson_sessions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`exam_attempt_id`) REFERENCES `exam_attempts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`ai_eval_call_id`) REFERENCES `ai_calls`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "attempts_context" CHECK("attempts"."context" IN ('lesson', 'review', 'reinforcement', 'exam', 'diagnostic', 'remediation')),
	CONSTRAINT "attempts_confidence" CHECK("attempts"."confidence" IS NULL OR "attempts"."confidence" IN ('sure', 'unsure', 'guessed')),
	CONSTRAINT "attempts_score_range" CHECK("attempts"."score" IS NULL OR ("attempts"."score" >= 0 AND "attempts"."score" <= 1)),
	CONSTRAINT "attempts_correct_bool" CHECK("attempts"."correct" IS NULL OR "attempts"."correct" IN (0, 1)),
	CONSTRAINT "attempts_rating" CHECK("attempts"."rating" IS NULL OR "attempts"."rating" IN (0, 1, 2, 3, 4)),
	CONSTRAINT "attempts_time_nonnegative" CHECK("attempts"."time_ms" IS NULL OR "attempts"."time_ms" >= 0),
	CONSTRAINT "attempts_tries_positive" CHECK("attempts"."tries" >= 1),
	CONSTRAINT "attempts_hints_nonnegative" CHECK("attempts"."hints_used" >= 0),
	CONSTRAINT "attempts_finished_after_started" CHECK("attempts"."finished_at" IS NULL OR "attempts"."finished_at" >= "attempts"."started_at"),
	CONSTRAINT "attempts_answer_json" CHECK("attempts"."answer" IS NULL OR json_valid("attempts"."answer")),
	CONSTRAINT "attempts_feedback_json" CHECK("attempts"."feedback" IS NULL OR json_valid("attempts"."feedback")),
	CONSTRAINT "attempts_id_uuidv7" CHECK(length("attempts"."id") = 36 AND substr("attempts"."id", 15, 1) = '7'),
	CONSTRAINT "attempts_version_positive" CHECK("attempts"."version" >= 1),
	CONSTRAINT "attempts_updated_after_created" CHECK("attempts"."updated_at" >= "attempts"."created_at")
);
--> statement-breakpoint
CREATE INDEX `attempts_activity` ON `attempts` (`activity_id`);--> statement-breakpoint
CREATE INDEX `attempts_session` ON `attempts` (`lesson_session_id`);--> statement-breakpoint
CREATE INDEX `attempts_exam_attempt` ON `attempts` (`exam_attempt_id`);--> statement-breakpoint
CREATE INDEX `attempts_card` ON `attempts` (`card_id`);--> statement-breakpoint
CREATE INDEX `attempts_started` ON `attempts` (`started_at`);--> statement-breakpoint
CREATE TABLE `lesson_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`lesson_id` text NOT NULL,
	`status` text DEFAULT 'in_progress' NOT NULL,
	`started_at` integer NOT NULL,
	`finished_at` integer,
	`duration_ms` integer,
	`xp` integer DEFAULT 0 NOT NULL,
	`accuracy` real,
	`activities_total` integer DEFAULT 0 NOT NULL,
	`activities_correct` integer DEFAULT 0 NOT NULL,
	`summary` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`lesson_id`) REFERENCES `lessons`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "lesson_sessions_status" CHECK("lesson_sessions"."status" IN ('in_progress', 'completed', 'abandoned')),
	CONSTRAINT "lesson_sessions_xp_nonnegative" CHECK("lesson_sessions"."xp" >= 0),
	CONSTRAINT "lesson_sessions_accuracy_range" CHECK("lesson_sessions"."accuracy" IS NULL OR ("lesson_sessions"."accuracy" >= 0 AND "lesson_sessions"."accuracy" <= 1)),
	CONSTRAINT "lesson_sessions_duration_nonnegative" CHECK("lesson_sessions"."duration_ms" IS NULL OR "lesson_sessions"."duration_ms" >= 0),
	CONSTRAINT "lesson_sessions_counts" CHECK("lesson_sessions"."activities_total" >= 0 AND "lesson_sessions"."activities_correct" >= 0 AND "lesson_sessions"."activities_correct" <= "lesson_sessions"."activities_total"),
	CONSTRAINT "lesson_sessions_finished_after_started" CHECK("lesson_sessions"."finished_at" IS NULL OR "lesson_sessions"."finished_at" >= "lesson_sessions"."started_at"),
	CONSTRAINT "lesson_sessions_summary_json" CHECK("lesson_sessions"."summary" IS NULL OR (json_valid("lesson_sessions"."summary") AND json_type("lesson_sessions"."summary") = 'object')),
	CONSTRAINT "lesson_sessions_id_uuidv7" CHECK(length("lesson_sessions"."id") = 36 AND substr("lesson_sessions"."id", 15, 1) = '7'),
	CONSTRAINT "lesson_sessions_version_positive" CHECK("lesson_sessions"."version" >= 1),
	CONSTRAINT "lesson_sessions_updated_after_created" CHECK("lesson_sessions"."updated_at" >= "lesson_sessions"."created_at")
);
--> statement-breakpoint
CREATE INDEX `lesson_sessions_lesson` ON `lesson_sessions` (`lesson_id`);--> statement-breakpoint
CREATE INDEX `lesson_sessions_started` ON `lesson_sessions` (`started_at`);--> statement-breakpoint
CREATE TABLE `review_logs` (
	`id` text PRIMARY KEY NOT NULL,
	`card_id` text NOT NULL,
	`rating` integer NOT NULL,
	`state` integer NOT NULL,
	`due` integer NOT NULL,
	`stability` real NOT NULL,
	`difficulty` real NOT NULL,
	`elapsed_days` integer NOT NULL,
	`scheduled_days` integer NOT NULL,
	`learning_steps` integer NOT NULL,
	`review` integer NOT NULL,
	`duration_ms` integer,
	`context` text NOT NULL,
	`exercise_score` real,
	`device` text,
	`attempt_id` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`attempt_id`) REFERENCES `attempts`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "review_logs_rating" CHECK("review_logs"."rating" IN (0, 1, 2, 3, 4)),
	CONSTRAINT "review_logs_state" CHECK("review_logs"."state" IN (0, 1, 2, 3)),
	CONSTRAINT "review_logs_context" CHECK("review_logs"."context" IN ('daily', 'lesson', 'reinforcement', 'exam_sim', 'cram', 'manual_postpone', 'import')),
	CONSTRAINT "review_logs_stability_nonnegative" CHECK("review_logs"."stability" >= 0),
	CONSTRAINT "review_logs_difficulty_range" CHECK("review_logs"."difficulty" >= 0 AND "review_logs"."difficulty" <= 10),
	CONSTRAINT "review_logs_elapsed_days_nonnegative" CHECK("review_logs"."elapsed_days" >= 0),
	CONSTRAINT "review_logs_scheduled_days_nonnegative" CHECK("review_logs"."scheduled_days" >= 0),
	CONSTRAINT "review_logs_learning_steps_nonnegative" CHECK("review_logs"."learning_steps" >= 0),
	CONSTRAINT "review_logs_duration_nonnegative" CHECK("review_logs"."duration_ms" IS NULL OR "review_logs"."duration_ms" >= 0),
	CONSTRAINT "review_logs_exercise_score_range" CHECK("review_logs"."exercise_score" IS NULL OR ("review_logs"."exercise_score" >= 0 AND "review_logs"."exercise_score" <= 1)),
	CONSTRAINT "review_logs_append_only" CHECK("review_logs"."updated_at" = "review_logs"."created_at" AND "review_logs"."version" = 1),
	CONSTRAINT "review_logs_id_uuidv7" CHECK(length("review_logs"."id") = 36 AND substr("review_logs"."id", 15, 1) = '7'),
	CONSTRAINT "review_logs_version_positive" CHECK("review_logs"."version" >= 1),
	CONSTRAINT "review_logs_updated_after_created" CHECK("review_logs"."updated_at" >= "review_logs"."created_at")
);
--> statement-breakpoint
CREATE INDEX `rl_card` ON `review_logs` (`card_id`,`review`);--> statement-breakpoint
CREATE INDEX `rl_review` ON `review_logs` (`review`);--> statement-breakpoint
CREATE INDEX `rl_attempt` ON `review_logs` (`attempt_id`);--> statement-breakpoint
CREATE TABLE `ai_calls` (
	`id` text PRIMARY KEY NOT NULL,
	`provider` text NOT NULL,
	`model` text NOT NULL,
	`role` text,
	`purpose` text NOT NULL,
	`status` text DEFAULT 'ok' NOT NULL,
	`input_tokens` integer DEFAULT 0 NOT NULL,
	`output_tokens` integer DEFAULT 0 NOT NULL,
	`cached_input_tokens` integer DEFAULT 0 NOT NULL,
	`reasoning_tokens` integer DEFAULT 0 NOT NULL,
	`cost_usd` real DEFAULT 0 NOT NULL,
	`latency_ms` integer,
	`batch_id` text,
	`custom_id` text,
	`prompt_version` text,
	`schema_version` text,
	`temperature` real,
	`job_id` text,
	`error` text,
	`meta` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`job_id`) REFERENCES `jobs`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ai_calls_status" CHECK("ai_calls"."status" IN ('ok', 'error')),
	CONSTRAINT "ai_calls_input_tokens_nonnegative" CHECK("ai_calls"."input_tokens" >= 0),
	CONSTRAINT "ai_calls_output_tokens_nonnegative" CHECK("ai_calls"."output_tokens" >= 0),
	CONSTRAINT "ai_calls_cached_tokens_nonnegative" CHECK("ai_calls"."cached_input_tokens" >= 0),
	CONSTRAINT "ai_calls_reasoning_tokens_nonnegative" CHECK("ai_calls"."reasoning_tokens" >= 0),
	CONSTRAINT "ai_calls_cost_nonnegative" CHECK("ai_calls"."cost_usd" >= 0),
	CONSTRAINT "ai_calls_latency_nonnegative" CHECK("ai_calls"."latency_ms" IS NULL OR "ai_calls"."latency_ms" >= 0),
	CONSTRAINT "ai_calls_temperature_range" CHECK("ai_calls"."temperature" IS NULL OR ("ai_calls"."temperature" >= 0 AND "ai_calls"."temperature" <= 2)),
	CONSTRAINT "ai_calls_meta_json" CHECK("ai_calls"."meta" IS NULL OR (json_valid("ai_calls"."meta") AND json_type("ai_calls"."meta") = 'object')),
	CONSTRAINT "ai_calls_id_uuidv7" CHECK(length("ai_calls"."id") = 36 AND substr("ai_calls"."id", 15, 1) = '7'),
	CONSTRAINT "ai_calls_version_positive" CHECK("ai_calls"."version" >= 1),
	CONSTRAINT "ai_calls_updated_after_created" CHECK("ai_calls"."updated_at" >= "ai_calls"."created_at")
);
--> statement-breakpoint
CREATE INDEX `ai_calls_created` ON `ai_calls` (`created_at`);--> statement-breakpoint
CREATE INDEX `ai_calls_provider_model` ON `ai_calls` (`provider`,`model`);--> statement-breakpoint
CREATE INDEX `ai_calls_job` ON `ai_calls` (`job_id`);--> statement-breakpoint
CREATE INDEX `ai_calls_custom_id` ON `ai_calls` (`custom_id`);--> statement-breakpoint
CREATE TABLE `jobs` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`status` text DEFAULT 'queued' NOT NULL,
	`priority` integer DEFAULT 0 NOT NULL,
	`payload` text NOT NULL,
	`result` text,
	`progress` text,
	`attempts` integer DEFAULT 0 NOT NULL,
	`max_attempts` integer DEFAULT 3 NOT NULL,
	`run_after` integer NOT NULL,
	`locked_by` text,
	`locked_at` integer,
	`started_at` integer,
	`finished_at` integer,
	`error` text,
	`parent_job_id` text,
	`subject_id` text,
	`idempotency_key` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`parent_job_id`) REFERENCES `jobs`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "jobs_status" CHECK("jobs"."status" IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
	CONSTRAINT "jobs_attempts_nonnegative" CHECK("jobs"."attempts" >= 0),
	CONSTRAINT "jobs_max_attempts_positive" CHECK("jobs"."max_attempts" >= 1),
	CONSTRAINT "jobs_payload_json" CHECK(json_valid("jobs"."payload") AND json_type("jobs"."payload") = 'object'),
	CONSTRAINT "jobs_result_json" CHECK("jobs"."result" IS NULL OR json_valid("jobs"."result")),
	CONSTRAINT "jobs_progress_json" CHECK("jobs"."progress" IS NULL OR (json_valid("jobs"."progress") AND json_type("jobs"."progress") = 'object')),
	CONSTRAINT "jobs_id_uuidv7" CHECK(length("jobs"."id") = 36 AND substr("jobs"."id", 15, 1) = '7'),
	CONSTRAINT "jobs_version_positive" CHECK("jobs"."version" >= 1),
	CONSTRAINT "jobs_updated_after_created" CHECK("jobs"."updated_at" >= "jobs"."created_at")
);
--> statement-breakpoint
CREATE INDEX `jobs_queue` ON `jobs` (`status`,`run_after`,`priority`);--> statement-breakpoint
CREATE INDEX `jobs_subject` ON `jobs` (`subject_id`);--> statement-breakpoint
CREATE INDEX `jobs_parent` ON `jobs` (`parent_job_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `jobs_idempotency_key_live` ON `jobs` (`idempotency_key`) WHERE "jobs"."idempotency_key" IS NOT NULL AND "jobs"."deleted_at" IS NULL;--> statement-breakpoint
CREATE TABLE `outbox` (
	`id` text PRIMARY KEY NOT NULL,
	`table_name` text NOT NULL,
	`row_id` text NOT NULL,
	`op` text NOT NULL,
	`row_version` integer NOT NULL,
	`payload` text,
	`synced_at` integer,
	`attempts` integer DEFAULT 0 NOT NULL,
	`error` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "outbox_op" CHECK("outbox"."op" IN ('insert', 'update', 'delete')),
	CONSTRAINT "outbox_row_version_positive" CHECK("outbox"."row_version" >= 1),
	CONSTRAINT "outbox_attempts_nonnegative" CHECK("outbox"."attempts" >= 0),
	CONSTRAINT "outbox_payload_json" CHECK("outbox"."payload" IS NULL OR (json_valid("outbox"."payload") AND json_type("outbox"."payload") = 'object')),
	CONSTRAINT "outbox_id_uuidv7" CHECK(length("outbox"."id") = 36 AND substr("outbox"."id", 15, 1) = '7'),
	CONSTRAINT "outbox_version_positive" CHECK("outbox"."version" >= 1),
	CONSTRAINT "outbox_updated_after_created" CHECK("outbox"."updated_at" >= "outbox"."created_at")
);
--> statement-breakpoint
CREATE INDEX `outbox_pending` ON `outbox` (`synced_at`,`created_at`);--> statement-breakpoint
CREATE INDEX `outbox_row` ON `outbox` (`table_name`,`row_id`);--> statement-breakpoint
CREATE TABLE `settings` (
	`id` text PRIMARY KEY NOT NULL,
	`key` text NOT NULL,
	`value` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`deleted_at` integer,
	`device_id` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "settings_key_nonempty" CHECK(length("settings"."key") > 0),
	CONSTRAINT "settings_value_json" CHECK(json_valid("settings"."value")),
	CONSTRAINT "settings_id_uuidv7" CHECK(length("settings"."id") = 36 AND substr("settings"."id", 15, 1) = '7'),
	CONSTRAINT "settings_version_positive" CHECK("settings"."version" >= 1),
	CONSTRAINT "settings_updated_after_created" CHECK("settings"."updated_at" >= "settings"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `settings_key_live` ON `settings` (`key`) WHERE "settings"."deleted_at" IS NULL;