-- 0008 — the chunker's identity columns, and `context` inside the FTS5 index.
--
-- Sub-phase 6.2 (docs/spec/05-ingestion-rag.md §4; docs/spec/04-path-generation.md §3
-- stage 2). Three columns on `chunks`, generated by drizzle-kit, and one thing it cannot
-- express: `chunks_fts` gains a `context` column, so the 50–100 tokens of contextual
-- retrieval are searchable next to the text they situate.
--
-- The columns are added with ALTER TABLE rather than the usual drizzle table rebuild. That
-- is deliberate and it is why `chunk_key` carries no hex CHECK: rebuilding `chunks` in
-- SQLite drops every trigger defined on it, which here means the FTS5 sync of migration
-- 0001 and the vec0 sync of 0001/0002 — five triggers this migration would then have to
-- restate, and keep in step with forever.
--
-- `src/migrator.ts` runs this file inside one transaction and verifies its hash on every
-- start; once applied it is never edited (docs/spec/00-conventions.md).

ALTER TABLE `chunks` ADD `chunk_key` text;--> statement-breakpoint
ALTER TABLE `chunks` ADD `chunking_version` text;--> statement-breakpoint
ALTER TABLE `chunks` ADD `is_frontmatter` integer DEFAULT false NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX `chunks_source_key` ON `chunks` (`source_id`,`chunk_key`);--> statement-breakpoint
CREATE INDEX `chunks_chunking_version` ON `chunks` (`chunking_version`);--> statement-breakpoint

-- `context` in the FTS5 index --------------------------------------------------------------
-- Anthropic's contextual-retrieval recipe indexes `context || text`: a paragraph that only
-- ever says "this phase" is then findable by the name the surrounding chapter gave it.
--
-- Here they are two columns rather than one concatenation, which buys the same recall and
-- two things a concatenation loses:
--   * `snippet()` keeps quoting the source. A citation must show what the book says, never
--     what a cheap model wrote about it, and column 2 stays the untouched chunk text.
--   * No phrase can match across the seam. Concatenated, a query for "…de la célula. En
--     este capítulo…" could match a boundary that exists in no document.
-- The context is weighted below the body in `src/search.ts` (`FTS_COLUMN_WEIGHTS`): a hit in
-- generated prose is weaker evidence than a hit in the source.
--
-- An FTS5 table's columns cannot be altered, so it is dropped, recreated and repopulated
-- from `chunks`. Nothing is lost: `chunks_fts` is derived data, and every row in it is one
-- SELECT away. `chunk_id` and `source_id` stay UNINDEXED and stay first, so the column
-- numbers `snippet()`/`highlight()` use for text and heading path do not move.
DROP TRIGGER `chunks_fts_ai`;--> statement-breakpoint
DROP TRIGGER `chunks_fts_au`;--> statement-breakpoint
DROP TRIGGER `chunks_fts_ad`;--> statement-breakpoint
DROP TABLE `chunks_fts`;--> statement-breakpoint
CREATE VIRTUAL TABLE `chunks_fts` USING fts5(
	`chunk_id` UNINDEXED,
	`source_id` UNINDEXED,
	`text`,
	`heading_path`,
	`context`,
	tokenize = 'unicode61 remove_diacritics 2'
);
--> statement-breakpoint
CREATE TRIGGER `chunks_fts_ai` AFTER INSERT ON `chunks`
WHEN new.`deleted_at` IS NULL
BEGIN
	INSERT INTO `chunks_fts` (`chunk_id`, `source_id`, `text`, `heading_path`, `context`)
	VALUES (new.`id`, new.`source_id`, new.`text`, new.`heading_path`, new.`context`);
END;
--> statement-breakpoint
-- `context` joins the watched columns: the contextualization job writes it long after the
-- chunk was inserted, and an index that did not notice would be the whole feature missing.
CREATE TRIGGER `chunks_fts_au` AFTER UPDATE OF `source_id`, `text`, `heading_path`, `context`, `deleted_at` ON `chunks`
BEGIN
	DELETE FROM `chunks_fts` WHERE `chunk_id` = old.`id`;
	INSERT INTO `chunks_fts` (`chunk_id`, `source_id`, `text`, `heading_path`, `context`)
	SELECT new.`id`, new.`source_id`, new.`text`, new.`heading_path`, new.`context`
	WHERE new.`deleted_at` IS NULL;
END;
--> statement-breakpoint
-- Domain rows are never hard-deleted; this only keeps the index honest if one ever is.
CREATE TRIGGER `chunks_fts_ad` AFTER DELETE ON `chunks`
BEGIN
	DELETE FROM `chunks_fts` WHERE `chunk_id` = old.`id`;
END;
--> statement-breakpoint
INSERT INTO `chunks_fts` (`chunk_id`, `source_id`, `text`, `heading_path`, `context`)
SELECT `id`, `source_id`, `text`, `heading_path`, `context` FROM `chunks` WHERE `deleted_at` IS NULL;
