import manifest from './manifest.json' with { type: 'json' }

/**
 * The local ONNX models the app can download and run
 * (`docs/spec/05-ingestion-rag.md` §3: "EmbeddingGemma/bge-m3 local by default",
 * "local: mxbai-rerank-base-v2 or bge-reranker-v2-m3").
 *
 * A catalog entry is the *whole* description of a model: which repository and commit it
 * comes from, exactly which files with which SHA-256, how wide its vectors are, how they are
 * reduced to the width of the index, which prompt prefixes it expects, and how its token
 * embeddings are pooled. That matters because the answer to "are these two vectors
 * comparable?" has to be a lookup, not a judgement — see `spaceId`.
 *
 * The hashes and the pinned revision are generated by `tooling/scripts/model-manifest.mjs`
 * (`pnpm run models:manifest`) and checked in; nothing downloads a file whose hash is not
 * listed here.
 */

export type ModelKind = 'embedding' | 'reranker'

/**
 * How a model's native vector is brought to `EMBEDDING_DIMENSIONS`.
 *
 * - `none` — the model already emits that width.
 * - `matryoshka` — the model was trained with Matryoshka Representation Learning (Kusupati
 *   et al. 2022), so a prefix of its vector is itself a valid embedding: truncate, then
 *   re-normalize. Lossy only in the way the model was trained to be.
 * - `random-projection` — the model was not, so a fixed, seeded Johnson–Lindenstrauss
 *   projection is used instead (`../embeddings/reduce.ts`). It preserves inner products up
 *   to a small distortion, which is what a ranking needs, and it is deterministic, which is
 *   what an index needs.
 */
export type DimensionReduction = 'none' | 'matryoshka' | 'random-projection'

/** How the token embeddings become one vector. BGE reads the `[CLS]` token; Gemma averages. */
export type Pooling = 'mean' | 'cls'

export interface ModelFile {
  /** Path inside the repository, and inside the model's directory on disk. */
  readonly path: string
  readonly bytes: number
  /** Lower-case hex SHA-256. Verified on download and on every load. */
  readonly sha256: string
}

export interface ModelSpec {
  /** Stable, short, ours: what settings store and what `spaceId` is built from. */
  readonly id: string
  readonly kind: ModelKind
  /** Hugging Face repository, which is also the directory layout transformers.js expects. */
  readonly repo: string
  /** Pinned commit. `main` moves; a moved `main` would invalidate every hash below. */
  readonly revision: string
  /**
   * transformers.js' `dtype`, verbatim — `q8`, `fp16`, `q4`…
   *
   * Note that the value and the file name are *different strings*: `q8` loads
   * `onnx/model_quantized.onnx`. Getting it wrong is silent — an unrecognised dtype falls
   * back to `fp32` and looks for `onnx/model.onnx`, which these repositories do not always
   * ship — so `graphFile()` derives the name and `catalog.test.ts` asserts the manifest
   * really lists it.
   */
  readonly dtype: string
  readonly files: readonly ModelFile[]
  /** Sum of `files[].bytes` — what the download dialog quotes. */
  readonly bytes: number
  /** The model's own output width. */
  readonly nativeDims: number
  /** The width stored in the index, after `reduction`. */
  readonly dims: number
  readonly reduction: DimensionReduction
  /** Context window in tokens; longer inputs are truncated by the tokenizer. */
  readonly maxTokens: number
  readonly pooling: Pooling
  /** Prepended to a search query before embedding it, when the model was trained with one. */
  readonly queryPrefix: string
  /** Prepended to a chunk before embedding it. */
  readonly documentPrefix: string
  readonly license: string
  /**
   * The identity of the vector space, written to `embeddings.model_id` and required by every
   * vector query — the spec's "store the `model_id` per embedding and never mix spaces".
   *
   * It carries the reduced width as well as the model, because a 768-wide truncation of a
   * 1024-wide model is a *different space* from the model's own output, and the two must
   * never end up in one KNN query. Everything that reduction depends on (the strategy, the
   * seed, the target width) is fixed by the catalog entry, so the id determines the space
   * completely: two vectors with the same `model_id` are always comparable.
   */
  readonly spaceId: string
}

/**
 * transformers.js' `dtype` → the graph file it loads. Mirrors `DEFAULT_DTYPE_SUFFIX_MAPPING`
 * in `@huggingface/transformers`; `tooling/scripts/model-manifest.mjs` keeps its own copy,
 * because it runs before this module exists.
 */
const DTYPE_SUFFIX: Record<string, string> = {
  fp32: '',
  fp16: '_fp16',
  int8: '_int8',
  uint8: '_uint8',
  q8: '_quantized',
  q4: '_q4',
  q4f16: '_q4f16',
  bnb4: '_bnb4',
}

/** The ONNX graph `spec.dtype` makes transformers.js load, relative to the model directory. */
export function graphFile(spec: Pick<ModelSpec, 'dtype' | 'id'>): string {
  const suffix = DTYPE_SUFFIX[spec.dtype]
  if (suffix === undefined) {
    throw new Error(`${spec.id} declares an unknown transformers.js dtype "${spec.dtype}"`)
  }
  return `onnx/model${suffix}.onnx`
}

/** The width of the app's vector index (`packages/db/src/search.ts`'s `EMBEDDING_DIMENSIONS`).
 *  Redeclared rather than imported: `ingest` does not depend on `db`. `models.test.ts`
 *  asserts the two agree. */
export const INDEX_DIMENSIONS = 768

interface ManifestEntry {
  id: string
  repo: string
  revision: string
  dtype: string
  files: { path: string; bytes: number; sha256: string }[]
}

/** Everything the manifest cannot know: it lists files and hashes, this lists behaviour. */
const TRAITS: Record<
  string,
  Omit<ModelSpec, 'id' | 'repo' | 'revision' | 'dtype' | 'files' | 'bytes' | 'spaceId'>
> = {
  'embeddinggemma-300m': {
    kind: 'embedding',
    nativeDims: 768,
    dims: INDEX_DIMENSIONS,
    reduction: 'none',
    maxTokens: 2048,
    pooling: 'mean',
    // The prompts the model card prescribes for retrieval. They are not decoration: an
    // EmbeddingGemma query embedded without `task: search result | query: ` lands in a
    // visibly different part of the space from the documents it is supposed to match.
    queryPrefix: 'task: search result | query: ',
    documentPrefix: 'title: none | text: ',
    license: 'gemma',
  },
  'bge-m3': {
    kind: 'embedding',
    nativeDims: 1024,
    dims: INDEX_DIMENSIONS,
    // Not a Matryoshka model, and 1024 ≠ the index's 768: a seeded JL projection is what
    // makes it storable at all without a second vec0 table per width.
    reduction: 'random-projection',
    maxTokens: 8192,
    pooling: 'cls',
    queryPrefix: '',
    documentPrefix: '',
    license: 'mit',
  },
  'bge-reranker-v2-m3': {
    kind: 'reranker',
    nativeDims: 1,
    dims: 1,
    reduction: 'none',
    maxTokens: 8192,
    pooling: 'cls',
    queryPrefix: '',
    documentPrefix: '',
    license: 'apache-2.0',
  },
}

function build(entry: ManifestEntry): ModelSpec {
  const traits = TRAITS[entry.id]
  if (traits === undefined) throw new Error(`model manifest has an unknown model "${entry.id}"`)
  // A dtype whose graph file the manifest does not list would fail at load time, on the
  // user's machine, after a 300 MB download. Fail here instead — at import, in every test.
  const graph = graphFile({ id: entry.id, dtype: entry.dtype })
  if (!entry.files.some((file) => file.path === graph)) {
    throw new Error(`${entry.id} declares dtype ${entry.dtype} but ships no ${graph}`)
  }
  return {
    ...traits,
    id: entry.id,
    repo: entry.repo,
    revision: entry.revision,
    dtype: entry.dtype,
    files: entry.files.map((file) => ({ ...file })),
    bytes: entry.files.reduce((sum, file) => sum + file.bytes, 0),
    spaceId: traits.kind === 'embedding' ? `${entry.id}@${traits.dims}` : entry.id,
  }
}

const SPECS: readonly ModelSpec[] = Object.freeze(
  (manifest.models as ManifestEntry[]).map(build).sort((a, b) => a.id.localeCompare(b.id)),
)

const BY_ID = new Map(SPECS.map((spec) => [spec.id, spec]))

/** Every model in the catalog, embedding and reranker alike. */
export function listModels(kind?: ModelKind): readonly ModelSpec[] {
  return kind === undefined ? SPECS : SPECS.filter((spec) => spec.kind === kind)
}

export function findModel(id: string): ModelSpec | undefined {
  return BY_ID.get(id)
}

/** Like `findModel`, but for the paths where an unknown id is a bug rather than a choice. */
export function requireModel(id: string, kind?: ModelKind): ModelSpec {
  const spec = BY_ID.get(id)
  if (spec === undefined) throw new Error(`No model "${id}" in the catalog`)
  if (kind !== undefined && spec.kind !== kind) {
    throw new Error(`Model "${id}" is a ${spec.kind} model, not a ${kind} one`)
  }
  return spec
}

/**
 * The default embedding model: EmbeddingGemma-300M, 768 dims, multilingual, ~300 MB
 * quantized — the spec's "EmbeddingGemma/bge-m3 local by default", with the Gemma first
 * because its native width *is* the index's, so nothing is reduced and nothing is lost.
 */
export const DEFAULT_EMBEDDING_MODEL_ID = 'embeddinggemma-300m'

/**
 * The default local reranker.
 *
 * `docs/spec/05-ingestion-rag.md` §3 names "mxbai-rerank-base-v2 or bge-reranker-v2-m3".
 * Only the second one publishes ONNX weights — `mixedbread-ai/mxbai-rerank-base-v2` ships
 * safetensors alone, which `@huggingface/transformers` cannot load — so bge is the one in
 * the catalog. Adding mxbai is a manifest entry and a `TRAITS` row the day an export exists.
 */
export const DEFAULT_RERANKER_MODEL_ID = 'bge-reranker-v2-m3'

/** Where a model's files live under the models root: the repo path, which is also the layout
 *  `@huggingface/transformers` resolves a local model from (`env.localModelPath`). */
export function modelDirectory(spec: ModelSpec): string {
  return spec.repo
}
