import {
  clampParameters,
  forgettingCurve,
  nextMemoryState,
  scheduledInterval,
} from '../memory/formulas'
import type { OptimizerCsvRow } from '../memory/optimizer-csv'
import { formatOptimizerCsv } from '../memory/optimizer-csv'
import { DEFAULT_FSRS_W } from '../memory/parameters'
import { hashString, mulberry32 } from '../memory/prng'
import type { Grade, MemoryState } from '../memory/types'

/**
 * A deterministic review history, generated *from* a known set of FSRS parameters.
 *
 * This is what makes "the optimizer improves log loss" a claim rather than a coin flip. The
 * history is not arbitrary noise: it is FSRS-6 sampled at `FIXTURE_GROUND_TRUTH_W`, a
 * different point in the same 21-parameter family than the published defaults. Recovering
 * something closer to that point is precisely the trainer's job, so a failure means
 * something real rather than an unlucky seed.
 *
 * It doubles as a cross-implementation check: the data is generated by *our* closed forms in
 * `memory/formulas.ts` and trained on by `fsrs-rs`'s Rust. If those two ever disagree
 * materially about the model, this fixture stops being learnable.
 */

export const FIXTURE_SEED = 'retenia-fsrs-optimizer-5k'

/**
 * How far the ground truth sits from the defaults, per parameter.
 *
 * Concentrated on `w0…w3` (the four initial stabilities, which §6 says are estimated first,
 * from the retention curves after the first and second review) and `w8…w10` (the growth of
 * stability after a success) — the parameters log loss is most sensitive to. Deliberately
 * *near* the defaults rather than adversarially far: a ground truth so distant that the
 * generated history is unlike anything FSRS produces would make the test fail for the wrong
 * reason.
 */
export const FIXTURE_PERTURBATION: readonly number[] = Object.freeze([
  1.6, 1.4, 0.7, 0.65, 1, 1, 1, 1, 1.35, 0.7, 1.3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.25,
])

export const FIXTURE_GROUND_TRUTH_W: readonly number[] = Object.freeze(
  clampParameters(
    DEFAULT_FSRS_W.map((value, index) => value * (FIXTURE_PERTURBATION[index] as number)),
  ),
)

export interface OptimizerFixtureOptions {
  cards?: number
  /** Reviews per card. The default gives ~5,000 rows over 800 cards. */
  reviewsPerCard?: number
  seed?: string
  startAt?: Date
  /** The retention the simulated learner schedules at. */
  desiredRetention?: number
  /**
   * Keep only the first this many rows, oldest first.
   *
   * Truncating by time is what a real export taken at a moment in time looks like — a
   * card whose later reviews fall outside the window simply has a shorter history — so it
   * costs the fixture nothing but makes its size an exact, stated number.
   */
  maxRows?: number
}

export interface OptimizerFixture {
  rows: OptimizerCsvRow[]
  csv: string
  /** The parameters the history was sampled from. */
  w: readonly number[]
}

const DAY_MS = 86_400_000

/** The size the CI fixture is described by: five thousand reviews. */
const DEFAULT_MAX_ROWS = 5_000

/** A UUIDv7-shaped id, so the rows look like the real table's. */
function cardId(index: number): string {
  return `019a0000-0000-7000-8000-${String(index).padStart(12, '0')}`
}

/**
 * Sample a history.
 *
 * Each card is introduced on a random day of the first year, then reviewed on the schedule
 * its own stability implies. Whether a review is recalled is drawn against the true
 * forgetting curve, so the data carries exactly the signal the optimizer is meant to find.
 */
export function generateOptimizerFixture(options: OptimizerFixtureOptions = {}): OptimizerFixture {
  const cards = options.cards ?? 800
  const reviewsPerCard = options.reviewsPerCard ?? 7
  const desiredRetention = options.desiredRetention ?? 0.9
  const w = FIXTURE_GROUND_TRUTH_W
  const w20 = w[20] as number
  const draw = mulberry32(hashString(options.seed ?? FIXTURE_SEED))
  const start = (options.startAt ?? new Date('2025-01-01T09:00:00.000Z')).getTime()

  const rows: OptimizerCsvRow[] = []
  for (let index = 0; index < cards; index += 1) {
    const id = cardId(index + 1)
    let at = start + Math.floor(draw() * 365) * DAY_MS
    let state: MemoryState | null = null
    // 0 New, 1 Learning, 2 Review, 3 Relearning — the `ts-fsrs` states the format carries.
    let cardState = 0
    let elapsed = 0

    for (let review = 0; review < reviewsPerCard; review += 1) {
      let grade: Grade
      if (state === null) {
        // The first answer, drawn from a plausible spread of first ratings.
        const roll = draw()
        grade = roll < 0.26 ? 1 : roll < 0.36 ? 2 : roll < 0.92 ? 3 : 4
      } else {
        const retrievability = forgettingCurve(elapsed, state.stability, w20)
        if (draw() < retrievability) {
          const roll = draw()
          grade = roll < 0.24 ? 2 : roll < 0.95 ? 3 : 4
        } else {
          grade = 1
        }
      }

      rows.push({
        cardId: id,
        reviewTime: at,
        reviewRating: grade,
        reviewState: cardState,
        // Milliseconds, in the range §13 calls the typical per-card time.
        reviewDuration: 3_000 + Math.floor(draw() * 12_000),
      })

      state = nextMemoryState(w, state, elapsed, grade, { shortTerm: false })
      cardState = grade === 1 ? 3 : 2
      elapsed = scheduledInterval(desiredRetention, state.stability, 36_500, w20)
      at += elapsed * DAY_MS
    }
  }

  rows.sort((a, b) => a.reviewTime - b.reviewTime || (a.cardId < b.cardId ? -1 : 1))
  const kept = rows.slice(0, options.maxRows ?? DEFAULT_MAX_ROWS)
  return { rows: kept, csv: formatOptimizerCsv(kept), w }
}
